class TransportWeapons {
    MACRO_ADDWEAPON(Binocular,50);
    MACRO_ADDWEAPON(ACE_Vector,20);
    MACRO_ADDWEAPON(Rangefinder,20);
    MACRO_ADDWEAPON(Trixie_Rangefinder,20);
    MACRO_ADDWEAPON(Trixie_Rangefinder_Tripod,20);
    MACRO_ADDWEAPON(Trixie_SOFLAM,10);
    MACRO_ADDWEAPON(Trixie_SOFLAM_Tripod,10);
    MACRO_ADDWEAPON(Trixie_SOFLAM_Tripod_ANPVS4,10);
};

class TransportMagazines {
    MACRO_ADDMAGAZINE(Laserbatteries,50);
    MACRO_ADDMAGAZINE(B_IR_Grenade,50);
    MACRO_ADDMAGAZINE(Chemlight_green,100);
    MACRO_ADDMAGAZINE(Chemlight_red,100);
    MACRO_ADDMAGAZINE(Chemlight_yellow,100);
    MACRO_ADDMAGAZINE(Chemlight_blue,100);
};

class TransportItems {
    MACRO_ADDITEM(ACE_Banana,5);
    MACRO_ADDITEM(ACE_EarPlugs,200);
    MACRO_ADDITEM(ItemWatch,100);
    MACRO_ADDITEM(ACE_Altimeter,100);
    MACRO_ADDITEM(ItemCompass,10);
    MACRO_ADDITEM(ACE_MapTools,100);
    MACRO_ADDITEM(ACE_microDAGR,100);
    MACRO_ADDITEM(ACE_ATragMX,10);
    MACRO_ADDITEM(ACE_Kestrel4500,10);
    MACRO_ADDITEM(ACE_SpareBarrel,20);
    MACRO_ADDITEM(ACE_IR_Strobe_Item,200);
    MACRO_ADDITEM(ToolKit,50);
    MACRO_ADDITEM(ACE_CableTie,200);
    MACRO_ADDITEM(ACE_wirecutter,20);
    MACRO_ADDITEM(ACE_key_west,100);
    MACRO_ADDITEM(ACE_key_lockpick,10);
    MACRO_ADDITEM(B_UavTerminal,50);
    MACRO_ADDITEM(ACE_UAVBattery,100);
    MACRO_ADDITEM(rhsusf_ANPVS_14,30);
    MACRO_ADDITEM(rhsusf_ANPVS_15,30);
    MACRO_ADDITEM(A3_GPNVG18_F,10);
    MACRO_ADDITEM(A3_GPNVG18_BLK_F,10);
    MACRO_ADDITEM(A3_GPNVG18b_F,10);
    MACRO_ADDITEM(A3_GPNVG18b_BLK_F,10);
    MACRO_ADDITEM(A3_GPNVG18_REC_F,10);
    MACRO_ADDITEM(A3_GPNVG18_REC_BLK_F,10);
    MACRO_ADDITEM(A3_GPNVG18b_REC_F,10);
    MACRO_ADDITEM(A3_GPNVG18b_REC_BLK_F,10);
};

class TransportBackpacks {
    MACRO_ADDBACKPACK(B_rhsusf_B_BACKPACK,2);
};